import { Router } from "express";
import attributesRoute from "./attributes.route";
import authRoute from "./auth.route";
import bannerRoute from "./banner.route";
import categoryRoute from "./category.route";
import customerRoute from "./customer.route";
import homeAboutRoute from "./homeAbout.route";
import masterRoute from "./master.route";
import staticPageRoute from "./staticPage.route";
import testimonialRoute from "./testimonial.route";
import roleRoute from "./role.route";
import uploadRoute from "./upload.route";
import userManagementRoute from "./user-management.route";
import productRoute from "./product.route";
import enquiriesUserRoute from "./frontend/enquiriesUser.route";
import enquiriesRoute from "./enquiries.route";
import companyinfoRoute from "./companyinfo.route";
import masterUserRoute from "./frontend/masterUser.route";
import homeAboutCustomerRoute from "./frontend/homeAbout-Customer.route";
import filterListData from "./frontend/flter-list-data.route";
import blogsRoute from "./blogs.route";
import orderRoute from "./order.route";
import paymentRoute from "./payment.route";
import subscriptionRoute from "./subscription.route";
import template2BannerRoute from "./template-2-banner.route";
import allProductAddCart from "./allProductAddCart";
import shopifyRoute from "./shopify/shopify.route";
import configProductNewRoute from "./configProductNew.route";
import reportsRoute from "./reports.route";
import looseDiamondRoute from "./loose-diamond.route";
import infoSectionRoute from "./info-section.route";
import templateThreeRoute from "./template-three.route";
import metaDataRoute from "./meta-data.route";
import couponRoute from "./coupon.route";
export default () => {
  const app = Router();
  authRoute(app);
  uploadRoute(app);
  bannerRoute(app);
  masterRoute(app);
  categoryRoute(app);
  staticPageRoute(app);
  testimonialRoute(app);
  customerRoute(app);
  attributesRoute(app);
  homeAboutRoute(app);
  roleRoute(app);
  userManagementRoute(app);
  productRoute(app);
  enquiriesUserRoute(app);
  enquiriesRoute(app);
  companyinfoRoute(app);
  masterUserRoute(app);
  homeAboutCustomerRoute(app);
  filterListData(app);
  blogsRoute(app);
  orderRoute(app);
  paymentRoute(app);
  template2BannerRoute(app);
  subscriptionRoute(app);
  allProductAddCart(app);
  configProductNewRoute(app);
  shopifyRoute(app);
  reportsRoute(app);
  looseDiamondRoute(app);
  infoSectionRoute(app);
  templateThreeRoute(app);
  metaDataRoute(app);
  couponRoute(app);
  return app;
};
